// <auto-generated />
using CrmCorretor.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrmCorretor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623034533_CriandoEstruturaInicial")]
    partial class CriandoEstruturaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("NomeCargo")
                        .HasColumnType("longtext");

                    b.HasKey("IdCargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Equipe", b =>
                {
                    b.Property<int>("IdEquipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEquipe"));

                    b.Property<int>("GerenteId")
                        .HasColumnType("int");

                    b.Property<int>("IdGerente")
                        .HasColumnType("int");

                    b.Property<string>("NomeEquipe")
                        .HasColumnType("longtext");

                    b.HasKey("IdEquipe");

                    b.HasIndex("GerenteId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("EmailUsuario")
                        .HasColumnType("longtext");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCreci")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaUsuario")
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CargoId");

                    b.HasIndex("IdEquipe");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Equipe", b =>
                {
                    b.HasOne("CrmCorretor.Models.Usuarios.Usuario", "Gerente")
                        .WithMany()
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Usuario", b =>
                {
                    b.HasOne("CrmCorretor.Models.Usuarios.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmCorretor.Models.Usuarios.Equipe", "Equipe")
                        .WithMany("Membros")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("CrmCorretor.Models.Usuarios.Equipe", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
